name: quranringkas
version: 1.0.1+7
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_theme_switcher: ^2.0.10
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dnd: ^0.1.4+1
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: ^2.3.13
  flutter_svg: ^2.0.9
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  just_audio: 0.9.36
  path_provider: 2.1.2
  scroll_to_index: 3.0.1
  share_plus: ^9.0.0
  sqflite: 2.3.2
  url_launcher: ^6.2.6
  wakelock_plus: ^1.2.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/json/
    - assets/json/juz/
  uses-material-design: true

flutter_icons:
  image_path: "assets/pngs/logonya2.png"
  android: true
  ios: true
  remove_alpha_ios: true
flutter_native_splash:
  android: true
  ios: true
  image: "assets/pngs/logosplashQR.png"
  color: "#102134"
